plugins {
    id 'java'
    id 'org.gretty' version '4.1.5'
}

repositories {
    mavenCentral()
}

java {
    sourceCompatibility = JavaVersion.VERSION_21
}

def jacksonDatabind = '2.17.0'
def jakartaServletApi = '6.1.0'
def springVersion = '6.1.13'
def lombokVersion = '1.18.34'
def hsqldbVersion = '2.7.3'
def aspectjWeaverVersion = '1.9.22'
def postgresVersion = '42.7.3'

dependencies {

    // Basic
    implementation group: 'com.fasterxml.jackson.core',
            name: 'jackson-databind',
            version: jacksonDatabind

    compileOnly group: 'jakarta.servlet',
            name: 'jakarta.servlet-api',
            version: jakartaServletApi

    // Spring
    implementation group: 'org.springframework',
            name: 'spring-context',
            version: springVersion

    implementation group: 'org.springframework',
            name: 'spring-jdbc',
            version: springVersion

    implementation group: 'org.springframework',
            name: 'spring-aop',
            version: springVersion

    // AOP
    implementation group: 'org.aspectj',
            name: 'aspectjweaver',
            version: aspectjWeaverVersion


    // db
    implementation group: 'org.postgresql',
            name: 'postgresql',
            version: postgresVersion

    implementation group: 'org.hsqldb',
            name: 'hsqldb',
            version: hsqldbVersion

    // Lombok
    compileOnly group: 'org.projectlombok',
            name: 'lombok',
            version: lombokVersion

    annotationProcessor group: 'org.projectlombok',
            name: 'lombok',
            version: lombokVersion
}

gretty {
    contextPath = '/'
}

