INSERT INTO users (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('user', '$2a$10$CEjgArcc/SVv1UIVfLVwS.7KZQZ6TaQoh13cTr6GCTTIjhee8TPLO', true, 'Jack');

INSERT INTO users (USERNAME, PASSWORD, ENABLED, FIRST_NAME)
VALUES ('admin', '$2a$10$WYpToaEC47cO0MY0mwMqJ.Vs79talyCtFCU7dANjh1n9BYBpu..Ju', true, 'Jill');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('user', 'ROLE_USER');

INSERT INTO AUTHORITIES (USERNAME, AUTHORITY)
VALUES ('admin', 'ROLE_ADMIN');