
DROP TABLE IF EXISTS orderr CASCADE;

DROP SEQUENCE IF EXISTS seq1 CASCADE;

CREATE SEQUENCE seq1 START WITH 1;

CREATE TABLE orderr (
  id BIGINT NOT NULL PRIMARY KEY DEFAULT nextval('seq1'),
  order_number VARCHAR(255) NOT NULL
);
